# Generated by Django 3.0 on 2024-12-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='delivery_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='addconsignmenttemp',
            name='delivery_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
