# Generated by Django 3.0 on 2024-12-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0003_lhsprem_lhstemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhsprem',
            name='DLNo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lhsprem',
            name='countGC',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lhsprem',
            name='ownerName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lhsprem',
            name='paidWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lhsprem',
            name='route_from',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lhsprem',
            name='route_to',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
