# Generated by Django 3.0 on 2024-12-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0008_turprem_turtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='delivery_type',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
